version: '3.9'
services:
  sharenow:
    container_name: sharenow-container
    build:
      context: .
      dockerfile: Dockerfile
      target: sharenow
    volumes:
     - shared-data:/opt/ShareNow
  
  nginx:
    container_name: nginx-container
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    volumes:
      - shared-data:/opt/ShareNow
    ports:
      - 8500:80

volumes:
  shared-data:
